"""
Django settings for Tienda_com project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as Mensajes_de_error


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c*q%!um0*(9l5j&b6)nz^usdn+yx^gu_y(&0ap=jj3t)k)_8)g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "pedidos",
    "crispy_forms",#aplicasion de crispy forms en el html registro
    "login",
    "carro",
    "Shop",
    "contacto",
    "blog",
    "WEB",
    "servicios",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Tienda_com.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'carro.context_processors.importe_total_carro',
            ],
        },
    },
]

WSGI_APPLICATION = 'Tienda_com.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases



# DATABASES = {
#    'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME':"gestionpersonal",
#         "USER": "postgres",
#         "PASSWORD": "**********",
#         "HOST":"127.0.0.1",
#         "DATABASE_PORT":"5432",
#     }
#  }


# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'Tienda',
#     }
# }




# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


DATABASES = {
    'default': {
        'ENGINE':'djongo',
        "NAME":"Tienda",
        'CLIENT': {
        "host":"mongodb+srv://Richidv:************@demodb.rnpom.mongodb.net/?retryWrites=true&w=majority",
            "username":"Richidv",
           "password":"************",
            "authMechanism":"SCRAM-SHA-1"
        }
    } 
}
    


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

#configuracion post para gmail.
EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST="smtp.gmail.com"
EMAIL_USE_TLS=True
EMAIL_PORT=587
EMAIL_HOST_USER="**************"
EMAIL_HOST_PASSWORD="**************"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





#____CRISPY_FORMS________________________________________________________
CRISPY_TEMPLATE_PACK="bootstrap4"

#The messages framework: documentacion en django 
MESSAGE_TAGS={

    Mensajes_de_error.DEBUG: "debug",
    Mensajes_de_error.INFO: "info",
    Mensajes_de_error.SUCCESS: "success",
    Mensajes_de_error.WARNING: "warning",
    Mensajes_de_error.ERROR: "danger",
}
